# Generated by Django 2.1.1 on 2019-02-06 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('instrument_purchase', models.CharField(max_length=100, null=True)),
                ('new_field', models.CharField(max_length=65, null=True)),
                ('house_no', models.CharField(max_length=100, null=True)),
                ('address_line1', models.CharField(max_length=100, null=True)),
                ('address_line2', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='UsageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_consumed', models.IntegerField()),
                ('units_produced', models.IntegerField()),
                ('units_transfered', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.GreenUser')),
            ],
        ),
    ]
